language: ruby
notifications:
  email: false
rvm:
  - 2.2.3
cache:
  - bundler
  - apt
addons:
  postgresql: "9.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.4 libpq-dev
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
  - bundle exec cucumber
